# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a33bdc7a3fa33e9108e0e62fa9931ff44ee304f32493f47a8925fef911ba1f7ff7d65e94ee9a28668085c9e5a57dcbe309af5958230d77c1ac7685706aaedcd

test:
  secret_key_base: 581f1fcb7cec1fe760741889b476f6ca339a50c2d7cab88e7a01eba02a591d647b93779935548c8d4519ab7cd0557f2f4793223d7f539b26e68e554c0cd0120c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
